language: r
distro: trusty
sudo: required
warnings_are_errors: false

addon:
  packages:
   - python-gdal
   - libgdal1-dev

# Code coverage
r_packages:
  - covr

before_script:
  - Rscript -e "install.packages('rgdal', type = 'source')"

after_success:
- Rscript -e 'library(covr); codecov()'
