language: r
distro: trusty
sudo: required
warnings_are_errors: false

addon:
  packages:
   - python-gdal
   - libgdal1-dev

r_binary_packages:
  - rgdal

# Code coverage
r_packages:
  - covr

before_script:
  - Rscript -e "install.packages('rgdal', type = 'source')"

## For a CRAN package
#  - ./travis-tool.sh install_r <package>

install:
  ## For installing all CRAN dependencies using rpack's DESCRIPTION
  - ./travis-tool.sh install_deps

after_success:
- Rscript -e 'library(covr); codecov()'
