language: r
dist: trusty
sudo: required
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - python-gdal

# Code coverage
r_packages:
  - covr
  - rgdal

## For a CRAN package
#  - ./travis-tool.sh install_r <package>

#install:
#  ## For installing all CRAN dependencies using rpack's DESCRIPTION
#  - ./travis-tool.sh install_deps

after_success:
- Rscript -e 'library(covr); codecov()'
