language: r
sudo: required
warnings_are_errors: false

addon:
  packages:
   - gdal-bin
   - libgdal1-dev
   - libproj-dev
   - python-gdal

# Code coverage
r_packages:
  - covr

r_binary_packages:
  - rgdal

after_success:
- Rscript -e 'library(covr); codecov()'
