language: r
dist: trusty
sudo: required
cache: packages
addons:
  apt:
    packages:
      - libgdal1h
      - libgdal1-dev
      - libproj-dev
      - python-gdal

# Code coverage
r_packages:
  - covr

before_script:
  - R -e "install.packages('rgdal', type = 'source')"

## For a CRAN package
#  - ./travis-tool.sh install_r <package>

#install:
#  ## For installing all CRAN dependencies using rpack's DESCRIPTION
#  - ./travis-tool.sh install_deps

after_success:
- Rscript -e 'library(covr); codecov()'
