language: r
r:
  - oldrel
  - release
  - devel
sudo: true

addon:
  packages:
   - gdal-bin
   - libgdal1-dev
   - libproj-dev

r_packages:
  - covr
  - rgdal

after_success:
- Rscript -e 'library(covr); codecov()'
