language: r
r:
  - oldrel
  - release
  - devel
distro: trusty
sudo: required

addon:
  packages:
   - gdal-bin
   - libgdal1-dev
   - libproj-dev

r_packages:
  - covr

r_binary_packages:
  - rgdal

after_success:
- Rscript -e 'library(covr); codecov()'
